version: "3.9"

services:

  # ======================
  # POSTGRESQL
  # ======================
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: akshayrathore
      POSTGRES_PASSWORD: root
      POSTGRES_DB: candlekart
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  # ======================
  # REDIS
  # ======================
  redis:
    image: redis:7
    container_name: redis
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - backend-network

  # ======================
  # ZOOKEEPER
  # ======================
  zookeeper:
    image: bitnami/zookeeper:3.8.4-debian-11-r17
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - backend-network


  # ======================
  # KAFKA
  # ======================
  kafka:
    image: bitnami/kafka:3.7.0-debian-11-r0
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL

      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9093:9093"
    networks:
      - backend-network


  # ======================
  # ELASTICSEARCH
  # ======================
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - backend-network
    ulimits:
      memlock:
        soft: -1
        hard: -1


  # ======================
  # EUREKA SERVER
  # ======================
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - backend-network

  # ======================
  # API GATEWAY
  # ======================
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"   # host:container
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - backend-network


  # ======================
  # CONNECTION
  # ======================
  connection:
    build: ./connection
    container_name: connection
    ports:
      - "8088:8080"   # host:container
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - backend-network

  # ======================
  # AUTH SERVICE
  # ======================
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8080"   # host:container
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
      - eureka-server
    networks:
      - backend-network

  # ======================
  # USER SERVICE
  # ======================
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8080"   # host:container
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
      - eureka-server
    networks:
      - backend-network

  # ======================
  # PRODUCT SERVICE
  # ======================
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8083:8080"   # host:container
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
      - eureka-server
      - kafka
    networks:
      - backend-network


# ======================
# VOLUMES
# ======================
volumes:
  postgres_data:
  redisdata:
  kafkadata:
  esdata:

# ======================
# NETWORK
# ======================
networks:
  backend-network:
    driver: bridge
